// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: app_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqAppStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId string `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
}

func (x *ReqAppStatus) Reset() {
	*x = ReqAppStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAppStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAppStatus) ProtoMessage() {}

func (x *ReqAppStatus) ProtoReflect() protoreflect.Message {
	mi := &file_app_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAppStatus.ProtoReflect.Descriptor instead.
func (*ReqAppStatus) Descriptor() ([]byte, []int) {
	return file_app_msg_proto_rawDescGZIP(), []int{0}
}

func (x *ReqAppStatus) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type AppStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AppId    int32  `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Priority int32  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Persist  int32  `protobuf:"varint,4,opt,name=persist,proto3" json:"persist,omitempty"`
	Status   bool   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AppStatus) Reset() {
	*x = AppStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppStatus) ProtoMessage() {}

func (x *AppStatus) ProtoReflect() protoreflect.Message {
	mi := &file_app_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppStatus.ProtoReflect.Descriptor instead.
func (*AppStatus) Descriptor() ([]byte, []int) {
	return file_app_msg_proto_rawDescGZIP(), []int{1}
}

func (x *AppStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppStatus) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AppStatus) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AppStatus) GetPersist() int32 {
	if x != nil {
		return x.Persist
	}
	return 0
}

func (x *AppStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type ResAppStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId    string       `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	MyId     int32        `protobuf:"varint,2,opt,name=my_id,json=myId,proto3" json:"my_id,omitempty"`
	Priority int32        `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Apps     []*AppStatus `protobuf:"bytes,4,rep,name=apps,proto3" json:"apps,omitempty"`
}

func (x *ResAppStatus) Reset() {
	*x = ResAppStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResAppStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResAppStatus) ProtoMessage() {}

func (x *ResAppStatus) ProtoReflect() protoreflect.Message {
	mi := &file_app_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResAppStatus.ProtoReflect.Descriptor instead.
func (*ResAppStatus) Descriptor() ([]byte, []int) {
	return file_app_msg_proto_rawDescGZIP(), []int{2}
}

func (x *ResAppStatus) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *ResAppStatus) GetMyId() int32 {
	if x != nil {
		return x.MyId
	}
	return 0
}

func (x *ResAppStatus) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ResAppStatus) GetApps() []*AppStatus {
	if x != nil {
		return x.Apps
	}
	return nil
}

var File_app_msg_proto protoreflect.FileDescriptor

var file_app_msg_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x70, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x25, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x41, 0x70, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x15, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x22, 0x84, 0x01, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65,
	0x72, 0x73, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x76, 0x0a,
	0x0c, 0x52, 0x65, 0x73, 0x41, 0x70, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a,
	0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x65, 0x66, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x04, 0x61, 0x70, 0x70, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x70, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x04, 0x61, 0x70, 0x70, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x75,
	0x6d, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_msg_proto_rawDescOnce sync.Once
	file_app_msg_proto_rawDescData = file_app_msg_proto_rawDesc
)

func file_app_msg_proto_rawDescGZIP() []byte {
	file_app_msg_proto_rawDescOnce.Do(func() {
		file_app_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_msg_proto_rawDescData)
	})
	return file_app_msg_proto_rawDescData
}

var file_app_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_msg_proto_goTypes = []interface{}{
	(*ReqAppStatus)(nil), // 0: ReqAppStatus
	(*AppStatus)(nil),    // 1: AppStatus
	(*ResAppStatus)(nil), // 2: ResAppStatus
}
var file_app_msg_proto_depIdxs = []int32{
	1, // 0: ResAppStatus.apps:type_name -> AppStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_msg_proto_init() }
func file_app_msg_proto_init() {
	if File_app_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAppStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResAppStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_msg_proto_goTypes,
		DependencyIndexes: file_app_msg_proto_depIdxs,
		MessageInfos:      file_app_msg_proto_msgTypes,
	}.Build()
	File_app_msg_proto = out.File
	file_app_msg_proto_rawDesc = nil
	file_app_msg_proto_goTypes = nil
	file_app_msg_proto_depIdxs = nil
}
