// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: check_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqLead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId string `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
}

func (x *ReqLead) Reset() {
	*x = ReqLead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_check_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLead) ProtoMessage() {}

func (x *ReqLead) ProtoReflect() protoreflect.Message {
	mi := &file_check_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLead.ProtoReflect.Descriptor instead.
func (*ReqLead) Descriptor() ([]byte, []int) {
	return file_check_msg_proto_rawDescGZIP(), []int{0}
}

func (x *ReqLead) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type ResLead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId string `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Ok    bool   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ResLead) Reset() {
	*x = ResLead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_check_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResLead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResLead) ProtoMessage() {}

func (x *ResLead) ProtoReflect() protoreflect.Message {
	mi := &file_check_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResLead.ProtoReflect.Descriptor instead.
func (*ResLead) Descriptor() ([]byte, []int) {
	return file_check_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ResLead) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *ResLead) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_check_msg_proto protoreflect.FileDescriptor

var file_check_msg_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x20, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x4c, 0x65, 0x61, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65,
	0x66, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x4c, 0x65, 0x61, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x72, 0x65, 0x66, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x75,
	0x6d, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_check_msg_proto_rawDescOnce sync.Once
	file_check_msg_proto_rawDescData = file_check_msg_proto_rawDesc
)

func file_check_msg_proto_rawDescGZIP() []byte {
	file_check_msg_proto_rawDescOnce.Do(func() {
		file_check_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_check_msg_proto_rawDescData)
	})
	return file_check_msg_proto_rawDescData
}

var file_check_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_check_msg_proto_goTypes = []interface{}{
	(*ReqLead)(nil), // 0: ReqLead
	(*ResLead)(nil), // 1: ResLead
}
var file_check_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_check_msg_proto_init() }
func file_check_msg_proto_init() {
	if File_check_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_check_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_check_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResLead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_check_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_check_msg_proto_goTypes,
		DependencyIndexes: file_check_msg_proto_depIdxs,
		MessageInfos:      file_check_msg_proto_msgTypes,
	}.Build()
	File_check_msg_proto = out.File
	file_check_msg_proto_rawDesc = nil
	file_check_msg_proto_goTypes = nil
	file_check_msg_proto_depIdxs = nil
}
