// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: ping_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId string `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
}

func (x *ReqPing) Reset() {
	*x = ReqPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPing) ProtoMessage() {}

func (x *ReqPing) ProtoReflect() protoreflect.Message {
	mi := &file_ping_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPing.ProtoReflect.Descriptor instead.
func (*ReqPing) Descriptor() ([]byte, []int) {
	return file_ping_msg_proto_rawDescGZIP(), []int{0}
}

func (x *ReqPing) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type ResPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId      string `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	MyId       int32  `protobuf:"varint,2,opt,name=my_id,json=myId,proto3" json:"my_id,omitempty"`
	Priority   int32  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	LeaderNode bool   `protobuf:"varint,4,opt,name=leader_node,json=leaderNode,proto3" json:"leader_node,omitempty"`
}

func (x *ResPing) Reset() {
	*x = ResPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ping_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResPing) ProtoMessage() {}

func (x *ResPing) ProtoReflect() protoreflect.Message {
	mi := &file_ping_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResPing.ProtoReflect.Descriptor instead.
func (*ResPing) Descriptor() ([]byte, []int) {
	return file_ping_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ResPing) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *ResPing) GetMyId() int32 {
	if x != nil {
		return x.MyId
	}
	return 0
}

func (x *ResPing) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ResPing) GetLeaderNode() bool {
	if x != nil {
		return x.LeaderNode
	}
	return false
}

var File_ping_msg_proto protoreflect.FileDescriptor

var file_ping_msg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x20, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x72,
	0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x66,
	0x49, 0x64, 0x22, 0x72, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x0a,
	0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x65, 0x66, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6d, 0x65, 0x64, 0x69,
	0x75, 0x6d, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ping_msg_proto_rawDescOnce sync.Once
	file_ping_msg_proto_rawDescData = file_ping_msg_proto_rawDesc
)

func file_ping_msg_proto_rawDescGZIP() []byte {
	file_ping_msg_proto_rawDescOnce.Do(func() {
		file_ping_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_ping_msg_proto_rawDescData)
	})
	return file_ping_msg_proto_rawDescData
}

var file_ping_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ping_msg_proto_goTypes = []interface{}{
	(*ReqPing)(nil), // 0: ReqPing
	(*ResPing)(nil), // 1: ResPing
}
var file_ping_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ping_msg_proto_init() }
func file_ping_msg_proto_init() {
	if File_ping_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ping_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ping_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ping_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ping_msg_proto_goTypes,
		DependencyIndexes: file_ping_msg_proto_depIdxs,
		MessageInfos:      file_ping_msg_proto_msgTypes,
	}.Build()
	File_ping_msg_proto = out.File
	file_ping_msg_proto_rawDesc = nil
	file_ping_msg_proto_goTypes = nil
	file_ping_msg_proto_depIdxs = nil
}
