// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: service_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enum int32

const (
	Enum_STOP  Enum = 0
	Enum_START Enum = 1
)

// Enum value maps for Enum.
var (
	Enum_name = map[int32]string{
		0: "STOP",
		1: "START",
	}
	Enum_value = map[string]int32{
		"STOP":  0,
		"START": 1,
	}
)

func (x Enum) Enum() *Enum {
	p := new(Enum)
	*p = x
	return p
}

func (x Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_service_msg_proto_enumTypes[0].Descriptor()
}

func (Enum) Type() protoreflect.EnumType {
	return &file_service_msg_proto_enumTypes[0]
}

func (x Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Enum.Descriptor instead.
func (Enum) EnumDescriptor() ([]byte, []int) {
	return file_service_msg_proto_rawDescGZIP(), []int{0}
}

type ReqAppService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId  string `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Action Enum   `protobuf:"varint,3,opt,name=action,proto3,enum=Enum" json:"action,omitempty"`
}

func (x *ReqAppService) Reset() {
	*x = ReqAppService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAppService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAppService) ProtoMessage() {}

func (x *ReqAppService) ProtoReflect() protoreflect.Message {
	mi := &file_service_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAppService.ProtoReflect.Descriptor instead.
func (*ReqAppService) Descriptor() ([]byte, []int) {
	return file_service_msg_proto_rawDescGZIP(), []int{0}
}

func (x *ReqAppService) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *ReqAppService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqAppService) GetAction() Enum {
	if x != nil {
		return x.Action
	}
	return Enum_STOP
}

type ResAppService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId string `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ok    bool   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ResAppService) Reset() {
	*x = ResAppService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResAppService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResAppService) ProtoMessage() {}

func (x *ResAppService) ProtoReflect() protoreflect.Message {
	mi := &file_service_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResAppService.ProtoReflect.Descriptor instead.
func (*ResAppService) Descriptor() ([]byte, []int) {
	return file_service_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ResAppService) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *ResAppService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResAppService) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_service_msg_proto protoreflect.FileDescriptor

var file_service_msg_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x41, 0x70, 0x70, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x05, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4a,
	0x0a, 0x0d, 0x52, 0x65, 0x73, 0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x2a, 0x1b, 0x0a, 0x04, 0x45, 0x6e,
	0x75, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6d, 0x65, 0x64,
	0x69, 0x75, 0x6d, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_msg_proto_rawDescOnce sync.Once
	file_service_msg_proto_rawDescData = file_service_msg_proto_rawDesc
)

func file_service_msg_proto_rawDescGZIP() []byte {
	file_service_msg_proto_rawDescOnce.Do(func() {
		file_service_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_msg_proto_rawDescData)
	})
	return file_service_msg_proto_rawDescData
}

var file_service_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_msg_proto_goTypes = []interface{}{
	(Enum)(0),             // 0: Enum
	(*ReqAppService)(nil), // 1: ReqAppService
	(*ResAppService)(nil), // 2: ResAppService
}
var file_service_msg_proto_depIdxs = []int32{
	0, // 0: ReqAppService.action:type_name -> Enum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_msg_proto_init() }
func file_service_msg_proto_init() {
	if File_service_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAppService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResAppService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_msg_proto_goTypes,
		DependencyIndexes: file_service_msg_proto_depIdxs,
		EnumInfos:         file_service_msg_proto_enumTypes,
		MessageInfos:      file_service_msg_proto_msgTypes,
	}.Build()
	File_service_msg_proto = out.File
	file_service_msg_proto_rawDesc = nil
	file_service_msg_proto_goTypes = nil
	file_service_msg_proto_depIdxs = nil
}
